apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/workload-identity

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: admin
    target:
      kind: Namespace
      version: v1
  - patch: |-
      - op: replace
        path: /metadata/name
        value: admin
    target:
      kind: ServiceAccount
      version: v1
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: admin
    target:
      kind: ServiceAccount
      version: v1