apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../../../../apps/admin/sbox/01
  # - ../../../../apps/azureserviceoperator-system/sbox/01
  # - ../../../../apps/kube-system/sbox/01

patches:
- path: kustomize.yaml